### PR TITLE
Fix issue #98, enjoy.py needs to be updated for new gym-minigrid

### PR DESCRIPTION
**Pull request by maximecb**
Fix problem outlined in issue #98

### CODE REVIEW

**Comment by maximecb** [comment]
@rizar once this is approved I'll update the BabyAI pip package as well.

**Comment by maximecb** [comment]
@dyth :)

**Comment by dyth** [comment]
I ran `./scripts/enjoy.py --env BabyAI-BossLevel-v0 --model BOT` and saw the bot complete some missions without crashing.
The code looks reasonable and I have no reason to suspect that it wouldn't work.

**Review by dyth — APPROVED** [review]

**Comment by jsyedidia** [comment]
Thank you for the quick fix! It seems to be working perfectly for me now.

**Comment by rizar** [comment]
Thank you for fixing this, @maximecb !

**Pull request merged**
