### PR TITLE
Two sets of keys for pickup/drop actions

### PR DESCRIPTION
**Pull request by maximecb**
In response to #100

### CODE REVIEW

**Comment by dyth** [comment]
Interesting failure.  Apparently blosc could not be installed.

**Comment by maximecb** [comment]
@rizar any issue what the problem with blosc is? IIRC we've run into this before. Hm.

**Comment by rizar** [comment]
I can't see the error message neither in this PR nor in #100. Am I missing something?

**Comment by maximecb** [comment]
It's failing to build blosc in travis-ci

**Comment by rizar** [comment]
I have never seen this before either. Quick googling did not help. I can
look into that this weekend.

**Comment by maximecb** [comment]
Ok thanks :)

**Comment by maximecb** [comment]
@rizar

**Comment by dyth** [comment]
could it be possible that the error was in Travis's end?  Could we just run the test again to check?

**Comment by maximecb** [comment]
I'll try restarting it.

**Comment by maximecb** [comment]
@dyth It passed. Still needs your approval to merge.

**Review by dyth — APPROVED** [review]

**Pull request merged**
